apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: assets-api-container
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "sh",
                    "-c",
                    "mkdir -p /srv/bucket && gcsfuse pixmob-csb-usce1-staging /srv/bucket",
                  ]
