apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: pixmob-staging
  name: security-policy
spec:
  description: "Cloud Armor security policy for the Assets API service (managed by: config connector)"
  type: CLOUD_ARMOR
  rule:
    - action: allow
      priority: 2147483647
      match:
        versionedExpr: SRC_IPS_V1
        config:
          srcIpRanges:
            - "*"