apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: production
resources:
  - ../base/
images:
  - name: cvere-client-image
    newName: us-central1-docker.pkg.dev/nuagir-prod/acr/cvere-client
    newTag: latest
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml