name: Build Docker image and deploy to GCP Cloud Run
on:
  push:
    branches:
      - main
jobs:
  docker_build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@v4
      - name: Setup the Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to the GCP Artifact Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.GCP_REGION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/acr/cvere-client:${{ github.sha }}"
            "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/acr/cvere-client:latest"
          build-args: |
            REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}
            REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  gcp_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@v4
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Deploy to GCP Cloud Run service
        run: |
          gcloud run deploy "${{ vars.GCP_CLOUD_RUN_SERVICE_NAME }}" \
            --image "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/acr/cvere-client:${{ github.sha }}" \
            --region "${{ vars.GCP_REGION }}"
    needs: docker_build